Bonnuocsonha/Controllers/Admin/Criteria/InfoCriteriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Bonnuocsonha.Models;
using PagedList;
using PagedList.Mvc;
using System.Globalization;
using System.Web.UI.WebControls;
using System.Web.UI;
using System.IO;
using System.Xml;
using System.Data.Entity;
namespace Bonnuocsonha.Controllers.Admin.Criteria
{
    public class InfoCriteriaController : Controller
    {
        private BonnuocsonhaContext db = new BonnuocsonhaContext();
        List<SelectListItem> carlists = new List<SelectListItem>();
        // GET: InfoCriteria
        public ActionResult Index(string id, FormCollection collection)
        {
            if ((Request.Cookies["Username"] == null))
            {
                return RedirectToAction("LoginIndex", "Login");
            }
            if (ClsCheckRole.CheckQuyen(6, 0, int.Parse(Request.Cookies["Username"].Values["UserID"])) == true)
            {
                var ListCriteria = db.tblInfoCriterias.OrderBy(m => m.Ord).ToList();
                var menuModel = db.tblGroupProducts.Where(m => m.ParentID == null).OrderBy(m => m.id).ToList();
                carlists.Clear();
                string strReturn = "---";
                foreach (var item in menuModel)
                {
                    carlists.Add(new SelectListItem { Text = item.Name, Value = item.id.ToString() });
                    StringClass.DropDownListFor(item.id, carlists, strReturn);
                    strReturn = "---";
                }
                if (id != "")
                {

                    ViewBag.drMenu = carlists;
                    ViewBag.idCate = id;
                    ViewBag.idMenu = id;
                }
                else
                {
                    ViewBag.drMenu = carlists;
                }
                if (collection["btnDelete"] != null)
                {
                    foreach (string key in Request.Form.Keys)
                    {
                        var checkbox = "";
                        if (key.StartsWith("chk_"))
                        {
                            checkbox = Request.Form["" + key];
                            if (checkbox != "false")
                            {
                                if (ClsCheckRole.CheckQuyen(6, 3, int.Parse(Request.Cookies["Username"].Values["UserID"])) == true)
                                {
                                    int ids = Convert.ToInt32(key.Remove(0, 4));
                                    tblInfoCriteria tblcriteria = db.tblInfoCriterias.Find(ids);
                                    db.tblInfoCriterias.Remove(tblcriteria);
                                    db.SaveChanges();
                                     
                                }
                                else
                                {
                                    return Redirect("/Users/Erro");

                                }
                            }
                        }
                    }
                    //dsd
                }
                if (Session["Thongbao"] != null && Session["Thongbao"] != "")
                {

                    ViewBag.thongbao = Session["Thongbao"].ToString();
                    Session["Thongbao"] = "";
                }
                return View();
            }
            else
            {
                return Redirect("/Users/Erro");

            }
        }
        public PartialViewResult partialCriteria(int? page, string text, string id, string idCate, string pageSizes)
        {
            var ListCriteria = db.tblInfoCriterias.OrderBy(p => p.Ord).ToList();

            int pageSize = 20;
            var pageNumber = (page ?? 1);
            // Thiết lập phân trang
            var ship = new PagedListRenderOptions
            {
                DisplayLinkToFirstPage = PagedListDisplayMode.Always,
                DisplayLinkToLastPage = PagedListDisplayMode.Always,
                DisplayLinkToPreviousPage = PagedListDisplayMode.Always,
                DisplayLinkToNextPage = PagedListDisplayMode.Always,
                DisplayLinkToIndividualPages = true,
                DisplayPageCountAndCurrentLocation = false,
                MaximumPageNumbersToDisplay = 5,
                DisplayEllipsesWhenNotShowingAllPageNumbers = true,
                EllipsesFormat = "&#8230;",
                LinkToFirstPageFormat = "Trang đầu",
                LinkToPreviousPageFormat = "«",
                LinkToIndividualPageFormat = "{0}",
                LinkToNextPageFormat = "»",
                LinkToLastPageFormat = "Trang cuối",
                PageCountAndCurrentLocationFormat = "Page {0} of {1}.",
                ItemSliceAndTotalFormat = "Showing items {0} through {1} of {2}.",
                FunctionToDisplayEachPageNumber = null,
                ClassToApplyToFirstListItemInPager = null,
                ClassToApplyToLastListItemInPager = null,
                ContainerDivClasses = new[] { "pagination-container" },
                UlElementClasses = new[] { "pagination" },
                LiElementClasses = Enumerable.Empty<string>()
            };
            ViewBag.ship = ship;
            if (pageSizes != null)
            {
                ViewBag.pageSizes = pageSizes;
                pageSize = int.Parse(pageSizes.ToString());
                ViewBag.chuoicout = "<span style='color: #A52A2A;'>" + pageSize + "</span> / <span style='color: #333;'>" + ListCriteria.Count.ToString() + "</span>";
                return PartialView(ListCriteria.ToPagedList(pageNumber, pageSize));

            }
            if (id != "" && id != null)
            {
                int idmenu = int.Parse(id);

                ListCriteria = db.tblInfoCriterias.Where(p => p.idCri == idmenu).OrderBy(m => m.Ord).ToList();
                if(idCate!=null && idCate!="")
                {
                    List<string> Mang = new List<string>();
                    int idCates=int.Parse(idCate);
                    var ListConnect = db.tblGroupCriterias.Where(p => p.idCate == idCates).ToList();
                    for(int i=0;i<ListConnect.Count;i++)
                    {
                        Mang.Add(ListConnect[i].idCri.ToString());
                    }
                    ListCriteria = db.tblInfoCriterias.Where(p => Mang.Contains(p.idCri.ToString())).OrderBy(m => m.Ord).ToList();
                }
                ViewBag.Idcha = id;
                return PartialView(ListCriteria.ToPagedList(pageNumber, pageSize));
            }
            else
            {
                ViewBag.Idcha = 0;
            }

            return PartialView(ListCriteria.ToPagedList(pageNumber, pageSize));
        }
        public ActionResult UpdateCriteria(string id, string Ord, string cbIsActive)
        {
            if (ClsCheckRole.CheckQuyen(6, 2, int.Parse(Request.Cookies["Username"].Values["UserID"])) == true)
            {
                int ids = int.Parse(id);
                var tblcriteria = db.tblInfoCriterias.Find(ids);
                tblcriteria.Active = bool.Parse(cbIsActive);
                tblcriteria.Ord = int.Parse(Ord);
                db.SaveChanges();
                var result = string.Empty;
                result = "Thành công";
                return Json(new { result = result });
            }
            else
            {
                var result = string.Empty;
                result = "Bạn không có quyền thay đổi tính năng này";
                return Json(new { result = result });
            }

        }
        public ActionResult DeleteCriteria(int id)
        {
            if (ClsCheckRole.CheckQuyen(6, 3, int.Parse(Request.Cookies["Username"].Values["UserID"])) == true)
            {
                tblInfoCriteria tblcriteria = db.tblInfoCriterias.Find(id);
                var result = string.Empty;
                db.tblInfoCriterias.Remove(tblcriteria);
                db.SaveChanges();
                 
                result = "Bạn đã xóa thành công.";
                return Json(new { result = result });
            }
            else
            {
                var result = string.Empty;
                result = "Bạn không có quyền thay đổi tính năng này";
                return Json(new { result = result });
            }

        }
        public ActionResult AutoOrd(string idCate)
        {

            int id = int.Parse(idCate);
            var ListOrd = db.tblInfoCriterias.Where(p => p.idCri == id).OrderByDescending(p => p.Ord).Take(1).ToList();
            var result = string.Empty;
            if (ListOrd.Count > 0)
            {
                int stt = int.Parse(ListOrd[0].Ord.ToString()) + 1;
                result = stt.ToString();
            }
            else
            {
                result = "0";

            }
            return Json(new { result = result });
        }
        public ActionResult Create(string id)
        {
            if ((Request.Cookies["Username"] == null))
            {
                return RedirectToAction("LoginIndex", "Login");
            }
            if (Session["Thongbao"] != null && Session["Thongbao"] != "")
            {

                ViewBag.thongbao = Session["Thongbao"].ToString();
                Session["Thongbao"] = "";
            }
            if (ClsCheckRole.CheckQuyen(6, 1, int.Parse(Request.Cookies["Username"].Values["UserID"])) == true)
            {
                 var menuModel = db.tblCriterias.OrderBy(m => m.id).ToList();
                List<SelectListItem> carlist = new List<SelectListItem>(); 
                foreach (var item in menuModel)
                {
                    carlist.Add(new SelectListItem { Text = item.Name, Value = item.id.ToString() });
                }
                if (id != null && id != "")
                    ViewBag.drMenu = new SelectList(carlist, "Value", "Text", id);
                else

Bonnuocsonha/Views/InfoCriteria/Create.cshtml
@{
    ViewBag.Title = "Thêm mới thuộc tính";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<script>
    $(document).ready(function () {
        $("#drMenu").change(function () {
            var idCate = $("#drMenu").val();
            $.ajax(
                   {
                       url: '/InfoCriteria/AutoOrd',
                       type: 'post',
                       data: { "idCate": idCate },
                       dataType: 'json',
                       success: function (data) {

                           $('#Ord').val(data.result);
                       }
                   ,
                       error: function () { }
           
                       //
                   });

        });
    });
</script>

@model Bonnuocsonha.Models.tblInfoCriteria

@using (Html.BeginForm("Create", "InfoCriteria", FormMethod.Post))
{   @Html.ValidationSummary(true)
    <div id="main-content">
        <div class="container-fluid">
            <div style="width: 100%; margin: 0 auto;">

                <div id="Breadcrumb" class="Block Breadcrumb ui-widget-content ui-corner-top ui-corner-bottom">
                    <ul>
                        <li><a href='/admin'><i class="icon-home" style="font-size:14px;"></i> Trang chủ</a></li>
                         <li class='Last'><span>Thêm mới thuộc tính</span></li>
                    </ul>
                </div>

                <div style="clear: both;"></div>

                <div id="cph_Main_ContentPane">
                    <div class="widget">
                        <!-- widget-title -->
                        <div class="widget-title">
                            <h4><i class="icon-reorder"></i>&nbsp;Thêm mới thuộc tính</h4>

                            <!-- Button -->
                            <div class="ui-widget-content ui-corner-top ui-corner-bottom">
                                <div id="toolbox">
                                    <div style="float:right;" class="toolbox-content">

                                        <table class="toolbar">
                                            <tr>

                                                <td align="center">
                                                    <button type="submit" class="toolbar btn btn-info" name="btnSave" id="btnSave"><i class="icon-save"></i> &nbsp;Lưu lại</button>

                                                </td>

                                                <td align="center">
                                                    <button type="submit" class="toolbar btn btn-info" name="btnSaveCreate" id="btnSaveCreate"><i class="icon-ok"></i> &nbsp;Lưu và Thêm mới</button>

                                                </td>
                                                <td align="center">
                                                    <a id="cph_Main_ctl00_toolbox_rptAction_lbtAction_4" title="Quay lại" style="color:#FFF !important" class="toolbar btn btn-info" href="">
                                                        <i class="icon-chevron-left"></i>&nbsp;
                                                        Quay lại
                                                    </a>
                                                </td>
                                                <td align="center">
                                                    <a onclick="" id="cph_Main_ctl00_toolbox_rptAction_lbtAction_0" title="Trợ giúp"  style="color:#FFF !important" class="toolbar btn btn-info" href="" )">
                                                        <i class="icon-question-sign"></i>&nbsp;
                                                        Trợ giúp
                                                    </a>
                                                </td>
                                            </tr>
                                        </table>

                                    </div>
                                </div>
                            </div>
                            <!-- End Button -->

                            <div id="hiddenToolBarScroll" class="scrollBox hidden">

                                <div class="FloatMenuBar" style="float:left; margin-left:20px">

                                    <div class="ui-widget-content ui-corner-top ui-corner-bottom">
                                        <div id="Div1">

                                            <div style="float:left;" class="toolbox-content">

                                                <table class="toolbar">
                                                    <tr>

                                                        <td align="center">
                                                            <button type="submit" class="toolbar btn btn-info" name="btnSave" id="btnSave"><i class="icon-save"></i> &nbsp;Lưu lại</button>

                                                        </td>

                                                        <td align="center">
                                                            <button type="submit" class="toolbar btn btn-info" name="btnSaveCreate" id="btnSaveCreate"><i class="icon-ok"></i> &nbsp;Lưu và Thêm mới</button>

                                                        </td>
                                                        <td align="center">
                                                            <a id="cph_Main_ctl00_toolbox_rptAction_lbtAction_4" title="Quay lại" style="color:#FFF !important" class="toolbar btn btn-info" href="">
                                                                <i class="icon-chevron-left"></i>&nbsp;
                                                                Quay lại
                                                            </a>
                                                        </td>
                                                        <td align="center">
                                                            <a onclick="" id="cph_Main_ctl00_toolbox_rptAction_lbtAction_0" title="Trợ giúp"  style="color:#FFF !important" class="toolbar btn btn-info" href="" )">
                                                                <i class="icon-question-sign"></i>&nbsp;
                                                                Trợ giúp
                                                            </a>
                                                        </td>
                                                    </tr>
                                                </table>

                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <!-- widget-title -->
                        <!-- widget-body -->
                        <div class="widget-body">
                            <div id="cph_Main_ctl00_notification_divNotice" style="padding-top:10px;">
                                <!-- Messange -->
                                @Html.Raw(ViewBag.thongbao)

                                <!-- End Messange -->
                            </div>
                            <table class="admintable" style="width: 100%;">
                                <tr>
                                    <td class="key">
                                        Danh mục cha <span class="Required">*</span>
                                    </td>
                                    <td>
                                        @Html.DropDownList("drMenu", "-- Danh mục cha --")


                                         <span class="tooltip-help">
                                            <span class="tooltipContent">
                                                <p class="tooltiptitle">
                                                    Danh mục cha
                                                </p>
                                                <p class="tooltipmessage">
                                                    Danh mục cấp trên của danh mục đang cập nhật
                                                </p>
                                            </span>
                                        </span>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="key">
                                        Tên thuộc tính <span class="Required">*</span>
                                    </td>
                                    <td>
                                        @Html.TextBoxFor(p => p.Name, new { @class = "Name_ad txtName", @autofocus = "autofocus", @required = "required" })


                                        <span class="tooltip-help">
                                            <span class="tooltipContent">
                                                <p class="tooltiptitle">
                                                    Tên tiêu trí
                                                </p>
                                                <p class="tooltipmessage">
                                                    Tên tiêu trí
                                                </p>
                                            </span>
                                        </span>
                                        <span class="Aler_ttxtName" style="color: #F00"></span>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="key">
                                        Đường dẫn<span class="Required">*</span>
                                    </td>
                                    <td>
                                        @Html.TextBoxFor(p => p.Url, new { @class = "Name_ad txtName", @autofocus = "autofocus" })


                                        <span class="tooltip-help">
                                            <span class="tooltipContent">
                                                <p class="tooltiptitle">
                                                    Đường dẫn URL
                                                </p>
                                                <p class="tooltipmessage">
                                                    Đường dẫn URL đến thuộc tính đó
                                                </p>
                                            </span>
                                        </span>
                                        <span class="Aler_ttxtName" style="color: #F00"></span>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="key">
                                        Thứ tự
                                    </td>
                                    <td>
                                        @Html.TextBoxFor(p => p.Ord, new { @class = "Ord_ad", @Value = @Html.Raw(ViewBag.Ord) })
                                        <span class="tooltip-help">
                                            <span class="tooltipContent">
                                                <p class="tooltiptitle">
                                                    Thứ tự hiển thị
                                                </p>
                                                <p class="tooltipmessage">
                                                    Thứ tự hiển thị
                                                </p>
                                            </span>
                                        </span>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="key">
                                        Hiển thị
                                    </td>
                                    <td>
                                        @{bool Active = true;}
                                        @Html.CheckBoxFor(model => Active)

                                        <span class="tooltip-help">
                                            <span class="tooltipContent">
                                                <p class="tooltiptitle">
                                                    Hiển thị
                                                </p>
                                                <p class="tooltipmessage">
                                                    Lựa chọn để danh mục sản phẩm hiển thị trên website
                                                </p>
                                            </span>
                                        </span>
                                    </td>
                                </tr>

                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
}

Bonnuocsonha/Views/InfoCriteria/partialCriteria.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<Bonnuocsonha.Models.tblInfoCriteria>
@using Bonnuocsonha.Models
<div id="ajaxnhan">
    <div class="row-fluid">
        <div class="span3">
            <div style="margin-top:18px;">
                Tổng số tiêu trí: @Html.Raw(ViewBag.chuoicout)
            </div>
        </div>
        <div class="span9">
            <div class="pagination pagination-small pagination-right">
                @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page, idcate = @ViewBag.idcate, pageSizes = @ViewBag.pageSizes, sortOrder = ViewBag.CurrentSortOrder, sortName = ViewBag.CurrentSortName, sortLevel = ViewBag.CurrentSortLevel }), (PagedListRenderOptions)ViewBag.ship)
            </div>

        </div>
    </div>
    <table class="table table-striped table-bordered dataTable table-hover" cellspacing="0" id="cph_Main_ctl00_ctl00_grvProducts" style="border-collapse:collapse;">
        <tr>
            <th scope="col">
                <input id="cph_Main_ctl00_ctl00_grvProducts_chkAll" type="checkbox" name="ctl00$cph_Main$ctl00$ctl00$grvProducts$ctl01$chkAll" onclick="javascript:SelectAllCheckboxes(this);" />
            </th>
            <th scope="col">Danh mục</th>
            <th scope="col">Số TT</th>
            <th scope="col">Trạng thái</th>

            <th scope="col">Thao tác</th>
        </tr>
        @foreach (var item in Model)
        {

            <tr class="row0">
                <td align="center" style="width:8px;">
                    <input id="chk_@item.id" type="checkbox" name="chk_@item.id" />

                </td>
                <td>
                    <a title="Sửa module @item.Name" href="../../InfoCriteria/Edit?id=@item.id" id="@Html.Raw("lbtUpdateProduct")@item.id"> @item.Name  </a>
                </td>
                <td class="OrderNumber" align="center" style="width:45px;">
                    <input type="text" id="txtOrderNumber" style="width: 30px;" value="@item.Ord" onchange="javascript:return UpdateCriteria(@item.id);" />
                </td>
                <td class="Active text-center" align="center" style="width:45px;">
                    @if (item.Active == true)
                    {
                        <input type="checkbox" id="cbIsActive" name="cbIsActive" value="true" checked onchange="javascript:return UpdateCriteria(@item.id);" />
                    }
                    else
                    {
                        <input type="checkbox" id="cbIsActive" name="cbIsActive" value="false" onchange="javascript:return UpdateCriteria(@item.id);" />
                    }
                </td>

                <td class="text-center" align="center" style="width:90px;">
                    <a class="action-link-button" title="Sửa" href="../../InfoCriteria/Edit?id=@item.id">
                        <i class="icon-edit"></i>
                    </a>
                    <a href="" class="action-link-button" id="@item.id" onclick="javascript:return DeleteCriteria(@item.id);" title="Xóa sản danh mục">
                        <i class="icon-trash"></i>
                    </a>
                </td>
            </tr>
        }

    </table>
    <div class="pagination pagination-small pagination-right">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page, idcate = @ViewBag.idcate, pageSizes = @ViewBag.pageSizes, sortOrder = ViewBag.CurrentSortOrder, sortName = ViewBag.CurrentSortName, sortLevel = ViewBag.CurrentSortLevel }), (PagedListRenderOptions)ViewBag.ship)
    </div>
</div>